### PR TITLE
Define NetClient, Fix Tests

### PR DESCRIPTION
**Pull request by lindleywhite**
NetClient is not defined within that file and the test was failing. Fix these to run.

### CODE REVIEW

**Comment by gobwas** [comment]
Hi @lindleywhite!

Thanks for the bug catch and your PR.

Im just trying to realize, why my and travis-ci's tests are not fail with that bug? 
How could I reproduce the situation, that you've catched?

**Comment by lindleywhite** [comment]
I'm using the driver on the browser and when I include the bowerized version, it threw an error with that NetClient not being defined. The tests you run are against Node, so maybe it's okay that you didn't define the NetClient object. The browser isn't so friendly.

**Comment by gobwas** [comment]
Im also run tests with karma in firefox on every build in travis... I will merge it soon, but just want to get the way it could be checked in unit tests in future.. )

**Comment by gobwas** [comment]
Just added "use strict" to bundle. Now in `0.5.1` version. Thanks! :beers:

**Pull request merged**
